### ISSUE TITLE
Use GitRepository and Kustomization method to install and manage Flux in cluster

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#3471]
# Details

**Describe the solution you'd like:**

Instead of embedding the gotk-components in my repo, install flux via their installation manifests from their GitRepo. e.g.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: v0.30.2
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # include only what's needed
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-installation
```

# bootstrap/kustomization.yaml

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/flux2/manifests/install?ref=v0.30.2
```

The method for install flux would be then to use a task like this:

```yaml
  flux:
    desc: "Bootstraps flux into the {{.CLUSTER_ENV}} cluster"
    run: once
    cmds:
      - kubectl --kubeconfig {{.KUBECONFIG}} apply --kustomize {{.KUBERNETES_DIR}}/bootstrap/
      - flux --kubeconfig {{.KUBECONFIG}} create secret git github-token
          --url=https://github.com/onedr0p/home-ops
          --username=git
          --password=blah
      - kubectl --kubeconfig {{.KUBECONFIG}} apply --kustomize {{.KUBERNETES_DIR}}/clusters/{{.CLUSTER_ENV}}/flux-system/
      - flux --kubeconfig {{.KUBECONFIG}} reconcile source git kubernetes
```
