### ISSUE TITLE
Renovate with system-upgrade-controller

### ISSUE THREAD

**Issue by reefland** [onedr0p/home-ops#3658]
# Details

I was poking around trying to understand how you handled the K3S `system-upgrade-controller` with `renovate`.  In looking at your plan files I see a reference to `channel: https://update.k3s.io/v1-release/channels/v1.24` - and I see reference to your [PR](https://github.com/onedr0p/home-ops/pull/3651)  being opened.

I experimented with adding the `channel` to my plan file and the upgrade controller immediately upgraded to latest version in the channel without renovate even running. 

I also looked at your `.github/renovate` directory, and nothing particular stood out as making the magic happen but I suspect I missed something in it.

I'm trying to get a PR opened for k3s upgrades by renovate.  (renovate is upgrading the upgrade-controller itself via PR, just not the K3S version)

**Comment by reefland** [comment]
I was afraid of that... you can sleep OK knowing the cluster can be upgraded at any random time?

It seems if you use the `version` instead of `channel` you can pin the k3s version to a specific version and control the upgrades.   But I was unable to figure out how to have renovate see that as a tag and associate that to `https://github.com/k3s-io/k3s-upgrade/releases/tag` tags.  Seems a renovate `regexManagers` should be able to handle it.

**Comment by onedr0p** [comment]
It's never broken on me ;) But I would be interested in renovate PR coming into upgrade it as well. Let me how you make out with that!

**Comment by onedr0p** [comment]
Actually, it wasn't that hard. This should work

https://github.com/onedr0p/home-ops/commit/3a9aa0413c00b023247dffffb6b1a40eeb28ce2b

**Comment by reefland** [comment]
So that is what I had minus the `# renovate: datasource=github-releases depName=k3s-io/k3s` which didn't work.  Does that comment give renovate a hint?

**Comment by onedr0p** [comment]
Yea that's picked up here 

https://github.com/onedr0p/home-ops/blob/main/.github/renovate.json5#L52L63

**Comment by reefland** [comment]
Maybe I'm missing something else needed in your renovate config? 

regexManagers section in `renovate.json`:

```
  "regexManagers": [
    {
      "description": "Update Democratic-csi docker image references",
      "fileMatch": ["^applications\\/democratic_csi_.*\\.ya?l$"],
      "matchStrings": ["image: (?<depName>.*?):(?<currentValue>.*?)\\s+"],
      "datasourceTemplate": "docker"
   },
   {
      "description": "Process various dependencies",
      "fileMatch": ["workloads/.+\\.ya?ml$"],
      "matchStrings": [
        "datasource=(?<datasource>\\S+) depName=(?<depName>\\S+)( versioning=(?<versioning>\\S+))?\n.*?\"(?<currentValue>.*)\"\n"
      ],
      "datasourceTemplate": "{{#if datasource}}{{{datasource}}}{{else}}github-releases{{/if}}",
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    },
    {
      "description": "Process raw GitHub URLs",
      "fileMatch": ["workloads/.+\\.ya?ml$"],
      "matchStrings": [
        "https:\\/\\/raw.githubusercontent.com\\/(?<depName>[\\w\\d\\-_]+\\/[\\w\\d\\-_]+)\\/(?<currentValue>[\\w\\d\\.\\-_]+)\\/.*"
      ],
      "datasourceTemplate": "github-releases",
      "versioningTemplate": "semver"
    }
  ]
```

Directory `applications\*` and `workloads\*` are my argocd paths, equivalent of your `cluster\*` and flux. 

`workloads/upgrade-controller/k3s-control-plan.yaml`:
```
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-control-node-plan
  namespace: system-upgrade
  labels:
    k3s-upgrade: control-node
spec:
  concurrency: 1 # Batch size (roughly maps to maximum number of unschedulable nodes)
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.23.5+k3s1
  # channel: https://update.k3s.io/v1-release/channels/v1.23
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: k3os.io/mode, operator: DoesNotExist}
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
```

Plenty of newer version than that.....  I get nothing from renovate:
```
 INFO: Repository started (repository=reefland/k3s-argocd-test)
       "renovateVersion": "32.120.0"
 INFO: Dependency extraction complete (repository=reefland/k3s-argocd-test)
       "baseBranch": "main",
       "stats": {
         "managers": {
           "argocd": {"fileCount": 14, "depCount": 14},
           "github-actions": {"fileCount": 2, "depCount": 4},
           "helmv3": {"fileCount": 3, "depCount": 3},
           "kustomize": {"fileCount": 3, "depCount": 4}
         },
         "total": {"fileCount": 22, "depCount": 25}
       }
 INFO: Repository finished (repository=reefland/k3s-argocd-test)
       "durationMs": 4220
```
