### ISSUE TITLE
Deploy gatus on router to monitor local systems

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4959]
It would be nice to run gatus on my router in order to check my local systems are up and operational. This should be less costly than having prometheus scrape certain things in which I do not need to visualize. 

Some examples of this are:

- ~~Ping PiKVM~~
- ~~Ping Tesmart KVM~~
- ~~Ping k8s nodes~~
- ~~Ping NAS~~
- ~~Ping Zigbee controller~~
- Port check containers on vyos are working
- etc...

**Comment by onedr0p** [comment]
# Config examples

## Pushover

```yaml
alerting:
  pushover:
    application-token: xxx
    user-key: xxx
```

## TCP

```yaml
endpoints:
  - name: zigbee-controller-tcp
    url: "tcp://zigbee-controller.turbo.ac:6638"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: pushover
        failure-threshold: 3
        success-threshold: 5
        send-on-resolved: true
        description: "healthcheck failed"
```

## ICMP

```yaml
endpoints:
  - name: zigbee-controller-icmp
    url: "icmp://zigbee-controller.turbo.ac"
    conditions:
      - "[CONNECTED] == true"
```

## DNS

```yaml
endpoints:
  - name: external-dns
    url: 192.168.254.2
    dns:
      query-name: "google.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.216.34"
      - "[DNS_RCODE] == NOERROR"
  - name: internal-dns
    url: 192.168.254.2
    dns:
      query-name: "something.turbo.ac"
      query-type: "A"
    conditions:
      - "[BODY] == 192.168.69.101"
      - "[DNS_RCODE] == NOERROR"
```

## HTTP

```yaml
endpoints:
  - name: website
    url: "http://zigbee-controller.turbo.ac"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
      - "[RESPONSE_TIME] < 300"
```
