### ISSUE TITLE
Issue with rewrite in immich ingress

### ISSUE THREAD

**Issue by mariusrugan** [onedr0p/home-ops#5157]
Hi,

First of all, thanks a lot for putting together all Immich components, in nice & understandable way,

I'm stuck - using Traefik as ingress at this point:

https://github.com/onedr0p/home-ops/blob/6a9a51665c29a5b7168beb7cffd8a77fd6dd8142/kubernetes/apps/default/immich/app/web/helmrelease.yaml#L59

I've created the same - i think - middleware:

```yaml
---
#
# nginx.ingress.kubernetes.io/configuration-snippet: rewrite /api/(.*) /$1 break;
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewrite-immich
  namespace: networking
spec:
  redirectRegex:
    regex: /api/(.*)
    replacement: /${1}
```
 
 it's applied to same ingress as you do in Ingress with nginx,
 
 ```yaml
     ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: localresolver
          # yamllint disable-line rule:line-length
          traefik.ingress.kubernetes.io/router.middlewares: networking-rewrite-immich@kubernetescrd
          hajimari.io/appName: "immich"
          hajimari.io/enable: "true"
          hajimari.io/icon: "web"
        hosts:
          - host: "pix.example.com"
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
 ```
  
 and i get the login screen (register admin user) but sign-up doesn't work.
namely: POST to https://pix.example.com, 405, 
```
{type: "error", error: {message: "POST method not allowed. No actions exist for this page"}} error: 
{message: "POST method not allowed. No actions exist for this page"} type : "error"
```

I am behind cloudflare, but i don't think that's the case, i can POST with other apps installed in the same domain. 
So i think it's the rewrite.

Any particular reason you put there is this /api to / (root) rewrite ?
Should the immich-server be behind an api.pix.example.com ?

Thanks a lot in advance.

**Comment by onedr0p** [comment]
I am not well-versed in Traefik these days as I find it more effort than it is worth to use it and do not like using it in Kubernetes.

Here's my thoughts on Traefik, and sorry to go off into a tangent:

- They want people to pay for the HA TLS implementation which they considered to be not great (using Consul) instead of using cert-manager.
- They do not want to support native cert-manager integration in their CRs but are willing to support external-dns in the future.
- Their CRs like `ingressroute` are painful and not needed 99% of the time over plain ingress annotations
- You should be using cert-manager so the built in acme support in Traefik is useless and does not scale
- The grafana dashboard for ingress-nginx is prettier than anything I've found for Traefik.
-  I can't name a single popular helm chart that supports the use of Traefik CRs.
-  ingress-nginx is a kubernetes-sigs project, which means support is much better and there is no ill-intentions that might be created by investors.

With that out of the way, you might want to use the immich-proxy container which is just nginx pre-configured to handle routing the requests. I used to use it before I was shown the way to do it without that pod.

See my deployments of immich at this commit

https://github.com/onedr0p/home-ops/blob/8df6908d8360bfe43e491f1d426592ebe275c864/kubernetes/apps/default/immich/app/proxy/helmrelease.yaml

**Comment by onedr0p** [comment]
I know this doesn't answer your question but I find more and more people migrating to ingress-nginx so it's hard to keep up with examples I've come across in the past on how to do XYZ using Traefik. You might want to try asking in the k8s@home or immich discord if you want to continue to try with what you are doing.

**Comment by mariusrugan** [comment]
You're right on all points wrt Traefik :) 

Right now i cannot give you a reason for using it, other than - it's legacy and at the root of everything.
I have to do a major overhaul to take it out.
I'm not using IngressRoute other than the dashboard, and yes, right now coasting with Ingress generated with annotations. I was maybe impressed at some point with TCP capabilities but never used them.

**Comment by onedr0p** [comment]
> I'm not using IngressRoute other than the dashboard

In that case migrating to ingress-nginx might be painless since all you need to do is swap annotations. I've done the migration in the past and it wasn't too hard, maybe took me 30 minutes overall. But I that might be harder if you are using OIDC/oauth2-proxy etc..

**Comment by mariusrugan** [comment]
Thanks for tip wrt immich-proxy, works ootb, issue can be closed.

**Comment by reefland** [comment]
I noticed you closed this out.  You attempted Immich with Traefik just before I was able to try myself.  I got it working without using the immich-proxy.   I'll put some notes here for future references.  An IngressRoute is not needed, just a middleware is needed.

1. An immich-server middleware is needed to strip the `/api` to just `/`:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: immich
  name: immich-server-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: true
```

2. Add a reference to this middleware file in the main kustomization file:
```
  - ./traefik-middleware.yaml
```

3. Unlike what @onedr0p provides, I separated the two ingress to their respective `values.yaml`.  The `immich-web` and `immich-server` now each have a single ingress.

Ingress for immich-server (api):
```
ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "immich-immich-server-stripprefix@kubernetescrd"
    hosts:
      - host: photos.<redacted-domain>
        paths:
          - path: /api
            pathType: Prefix
            service:
              name: immich-server
              port: 3001
```
* The annotation for `entrypoints` resolves to my secure HTTPS port (443 to 8443).
* The annotation for `middlewares` is the path to the `stripprefix` middleware created above.  It uses `<namespace>-<middleware_name>@kubernetescrd"`.  If you want to include additional middlewares, just use a comma separated list within that string.

And then the immich-web gets its respective ingress:
```ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hosts:
      - host: photos.<redacted-domain>
        paths:
          - path: /
            pathType: Prefix
            service:
              name: immich-web
              port: 3000
```

Now within Traefik, you will have the two ingress:
![image](https://user-images.githubusercontent.com/16230914/232903548-6c634a37-009a-4f49-8e14-808ffa36abfa.png)

When viewing the details of the immich-server path, the middleware is reflected:
![image](https://user-images.githubusercontent.com/16230914/232904548-91f1fbe9-6e3a-4c70-8455-388893e782a1.png)

And Immich fires right up:
![image](https://user-images.githubusercontent.com/16230914/232904781-f079f4e9-005f-4778-9b8f-5521b9e5c56e.png)
