### ISSUE TITLE
Q: Samsung 970 EVO Plus with Ceph

### ISSUE THREAD

**Issue by reefland** [onedr0p/home-ops#5853]
When you have a moment, question on how you feel the Samsung 970 Evo Plus are doing with Ceph.  I noticed you were using them exclusively.
```
        nodes:
          - name: k8s-0
            devices:
              - name: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NJ0TB03807K
          - name: k8s-1
            devices:
              - name: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NS0W223961P
          - name: k8s-2
....
```

I was using Samsung 980 1TB NVMe (not Pro version) and started having issues after reaching 80+ TBW (rated for 600 TBW).
* Neither `smartd` nor `nvme-cli` report any errors.
* However, nightly I was having Ceph Scrub errors.
* PG damaged messages, constantly point to the same OSD (different PG each time, but always same OSD).

Did some research and community seems to feel generally, 970 EVO plus is a better option over 980 as the 970 has DRAM cache and should be more reliable over several years. The 2TB version is rated for 1200 TBW.

I swapped out the troublesome 1TB 980 with a 2TB 970 Evo Plus - no scrub errors since. However, **the temperature!**  It's running at 60C to 65C (~143F) with a 3rd party heat sink on it.  I recall you use small mini PCs as well which lack any decent airflow.

Have you had any issues with the temperatures? Reliability? You plan on sticking with these in the future?

---

I also noticed there is some `smartd` issue with 970 Pus models where it queries the controller with an INVALID_FIELD which is logged every time.  Apparently a known issue and just supposed to ignore it:
```
$ sudo nvme error-log -e 1 /dev/nvme0

Error Log Entries for device:nvme0 entries:1
.................
 Entry[ 0]   
.................
error_count     : 28
sqid            : 0
cmdid           : 0x4018
status_field    : 0x2002(INVALID_FIELD: A reserved coded value or an unsupported value in a defined field)
phase_tag       : 0
parm_err_loc    : 0xffff
lba             : 0
nsid            : 0
vs              : 0
trtype          : The transport type is not indicated or the error is not transport related.
cs              : 0
trtype_spec_info: 0
.................
```
