### ISSUE TITLE
Set an affinity for ceph mgr and mons to be on my master nodes

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#6566]
This would be nice to know where they are scheduled in the future. It will require a cluster rebuild to make happen.

https://github.com/buroa/k8s-gitops/blob/5657962162d076b4380dd51ec7ed59d83542a5b7/kubernetes/apps/rook-ceph/rook-ceph/cluster/helmrelease.yaml#L84-L95

```yaml
      placement:
        mgr:
          nodeAffinity: &nodeAffinity
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exist
        mon:
          nodeAffinity: *nodeAffinity
```
