### ISSUE TITLE
Add `PushSecret` config for Ceph RGW buckets for Thanos

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#6605]
I am manually syncing the s3 key and secret key secrets to 1Password, this can change if the below PR gets merged and a release is cut.

https://github.com/external-secrets/external-secrets/pull/2646

```yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: thanos-rgw
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: thanos-bucket-v2
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: thanos-rgw
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: thanos-rgw
```
