### ISSUE TITLE
Home Assistan Environment variables

### ISSUE THREAD

**Issue by jsantosa-minsait** [onedr0p/home-ops#7686]
### Describe the bug or feature request

Hi!

Really amazing job with the home-ops repository and custom images!! 🥹 

Since I am using a reverse proxy (ingress) to access Home Assistant Web UI, I have to configure trusted proxies in order to be able to get into the dashboard. I am using the envs (HASS_HTTP_TRUSTED_PROXY_1 and HASS_HTTP_TRUSTED_PROXY_2) but when I am trying to get into the configuration there is nothing being updated, so I have to add those values manually. Is this the expected behavior? 

configuration.yaml

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !env_var HASS_HTTP_TRUSTED_PROXY_1
    - !env_var HASS_HTTP_TRUSTED_PROXY_2
  ip_ban_enabled: true
  login_attempts_threshold: 5
```

Thanks in advance.
Javier

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
