### ISSUE TITLE
Revisit logging

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#7794]
Things to reconsider:
- Using Vector agent and aggregator
- Using Loki simple scalable

Loki `simplescalable` is a bit much but it does provide the one feature I need which is alerting on log messages. I tried loki `singlebinary` but found that the `k8s-sidecar` doesn't work with it. https://github.com/grafana/loki/issues/10967

I would love to have some simple solution for logging that still allows me to alert on log msg defined in code. Grafana integration isn't required by a nice-to-have.

**Comment by onedr0p** [comment]
I have went to a singlebinary loki deployment using promtail over vector. One issue to solve is log alerts

**Comment by gwelican** [comment]
I am not sure if you found a solution for log alerts, but I recently had the same trouble, hacked a kustomize patch to inject the k8s-sidecar:

```
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: loki
    patch: |
      - op: add
        path: /spec/template/spec/containers/-
        value:
          name: config-sync
          image: ghcr.io/kiwigrid/k8s-sidecar:1.27.6
          env:
            - name: FOLDER
              value: /var/loki/rules/fake
            - name: LABEL
              value: loki_rule
            - name: NAMESPACE
              value: ALL
            - name: RESOURCE
              value: both
            - name: UNIQUE_FILENAMES
              value: 'true'
            - name: METHOD
              value: WATCH
          volumeMounts:
            - mountPath: /var/loki
              name: storage
```

and I had to add this config to match the sidecar:


```  
structuredConfig:
    ruler:
      enable_alertmanager_v2: true
      alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
      enable_api: true
      storage:
        type: local
        local:
          directory: /var/loki/rules
      rule_path: /var/loki/rules/fake
 ```
