### ISSUE TITLE
Migrate to Talos `UserVolumeConfig`

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#9296]
### Describe the bug or feature request

1. The following can be placed in https://github.com/onedr0p/home-ops/blob/main/talos/controlplane.yaml.j2

	```yaml
	---
	apiVersion: v1alpha1
	kind: UserVolumeConfig
	name: local-hostpath
	provisioning:
	  diskSelector:
	    match: disk.model == "Corsair MP600 MICRO" && !system_disk
      minSize: 1TB
	```

2. Openebs then needs the mount to be updated to `/var/mnt/local-hostpath`
3. Remove `extraMounts` in https://github.com/onedr0p/home-ops/blob/main/talos/controlplane.yaml.j2
4. Remove disks in each node config.
5. Determine if disk needs to be wiped on cluster rebuild.

Ref: https://www.talos.dev/v1.10/reference/configuration/block/uservolumeconfig/

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
